version: "3"

services:
  delete-indexes:
    image: playdingnow/delete-outdated-es-indexes:1.3
    environment:
      - eshost=elasticsearch
      - esport=92003
      - esmaxdays=30
  elasticsearch:
    image: elasticsearch
    build: ./dockerfiles/elasticsearch
    environment:
      - xpack.security.enabled=false
      - reindex.remote.whitelist=192.168.69.30:9200
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data/
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.1
    ports:
      - 5601:5601
    volumes:
      - ./kibana/data:/usr/share/kibana/data/
    depends_on:
      - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:6.5.1
    ports:
      - 5010:5010
      - 5044:5044
      - 8888:8888
    environment:
      - ES_HOSTS='http://elasticsearch:9200'
  apm-server:
    image: docker.elastic.co/apm/apm-server:6.5.1
    ports:
      - 8200:8200
    environment:
      - output.elasticsearch.hosts=['http://elasticsearch:9200']
      - xpack.monitoring.enabled=true
      - apm-server.host="0.0.0.0:8200"
      - apm-server.secret_token="xxVpmQB2HMzCL9PgBHVrnxjNXXw5J7bd79DFm6sjBJR5HPXDhcF8MSb3vv4bpg44"
      - setup.kibana.host="kibana:5601"
      - setup.template.enabled=true
      - logging.to_files=false
    depends_on:
      - elasticsearch
      - kibana
